//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AQ.Kelloggs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AQ.Kelloggs.UI.App_LocalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult(18 - 70 yrs).
        /// </summary>
        public static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOV : Correspondence Maps.
        /// </summary>
        public static string CorrespondenceMaps {
            get {
                return ResourceManager.GetString("CorrespondenceMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOV : Visual Cross Tab.
        /// </summary>
        public static string CrossTab {
            get {
                return ResourceManager.GetString("CrossTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOV : My Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOV : Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids(4 -12 yrs).
        /// </summary>
        public static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOV : Occasion Profile.
        /// </summary>
        public static string OccasionProfile {
            get {
                return ResourceManager.GetString("OccasionProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OccassionProfile.
        /// </summary>
        public static string OccassionProfileURL {
            get {
                return ResourceManager.GetString("OccassionProfileURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOV : Occasion Strategic Postures.
        /// </summary>
        public static string OSP {
            get {
                return ResourceManager.GetString("OSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOV : Occasion Performance Dashboard.
        /// </summary>
        public static string PerformanceDashboard {
            get {
                return ResourceManager.GetString("PerformanceDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOV : Report Generator.
        /// </summary>
        public static string ReportGenerator {
            get {
                return ResourceManager.GetString("ReportGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teen(13 - 17 yrs).
        /// </summary>
        public static string Teen {
            get {
                return ResourceManager.GetString("Teen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOV : User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
    }
}
